
define: &the_stage pre-commit

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.7
  hooks:
    # Run the linter.
    - id: ruff
      stages: [*the_stage]
    # Run the formatter.
    # - id: ruff-format
    #   args: [ --diff ]
    #   stages: [*the_stage]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-illegal-windows-names
        stages: [*the_stage]
    -   id: check-json
        stages: [*the_stage]
    -   id: check-toml
        stages: [*the_stage]
    -   id: check-yaml
        stages: [*the_stage]
    -   id: debug-statements
        stages: [*the_stage]
    -   id: destroyed-symlinks
        stages: [*the_stage]
    -   id: detect-private-key
        stages: [*the_stage]
    -   id: name-tests-test
        args: [ --pytest-test-first ]
        stages: [*the_stage]
    -   id: trailing-whitespace
        stages: [*the_stage]

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.25.1
    hooks:
    -   id: gitleaks
        stages: [*the_stage]


-   repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
    -   id: typos
        stages: [*the_stage]



-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies: [pytest]
        stages: [*the_stage]


-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        stages: [*the_stage]


-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.6.0
    hooks:
      - id: commitizen
        stages: [commit-msg]


-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    -   id: gitlint
        stages: [commit-msg]

