
name: Ruff Linter & Formatter


on:
  workflow_dispatch:

jobs:
  ruff_lint_N_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      run: uv sync --dev


    # - name: Install the code linting and formatting tool Ruff
    #   run: uv pip install ruff
    - name: Lint code with Ruff
      run: uv ruff check --output-format=github --target-version=py313
    - name: Check code formatting with Ruff
      run: uv ruff format --diff --target-version=py313
      continue-on-error: true

