
name: Ruff Linter & Formatter


on:
  workflow_dispatch:

jobs:
  ruff_lint_N_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install the code linting and formatting tool Ruff
      run: pipx install ruff
    - name: Lint code with Ruff
      run: ruff check --output-format=github --target-version=py313
    - name: Check code formatting with Ruff
      run: ruff format --diff --target-version=py313
      continue-on-error: true


# Integrate with uv, install dependencies and use cache

