
name: Mypy


on:
  workflow_dispatch:

jobs:
  ruff_lint_N_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4



    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
        cache: 'pip' # caching pip dependencies

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        python -m pip install mypy

    - name: Run static type checking (`mypy`)
      run: python -m mypy

